steps:
  - trigger: elasticsearch-serverless
    label: ":elasticsearch: Run serverless tests"
    branches: override_submodule_commit
    build:
      env:
        ELASTICSEARCH_SUBMODULE_COMMIT: "${BUILDKITE_COMMIT}"

  - wait:

  - label: ":git: Update elasticsearch submodule commit"
    commands:
      - "git commit -m 'Update elasticsearch submodule'"
      - "git push origin"

