steps:
  - trigger: elasticsearch-serverless
    label: ":elasticsearch: Run serverless tests"
    build:
      branch: override_submodule_commit
      message: "Elasticsearch submodule promotion build"
      env:
        ELASTICSEARCH_SUBMODULE_COMMIT: "${BUILDKITE_COMMIT}"

