steps:
  - label: third-party-tests-azure
    command: |-
      set -euo pipefail
      set +x
      #VAULT_TOKEN=$$(vault write -field=token auth/approle/login role_id=$$VAULT_ROLE_ID secret_id=$$VAULT_SECRET_ID)
      export VAULT_TOKEN
      export data=$$(vault read -format=json secret/ci/elastic-elasticsearch/migrated/azure_thirdparty_test_creds)
      export azure_storage_account=$$(echo $$data | jq -r .data.account_id)
      export azure_storage_key=$$(echo $$data | jq -r .data.account_key)
      unset data
      set -x

      .ci/scripts/run-gradle.sh azureThirdPartyTest
    timeout_in_minutes: 180
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
  - label: third-party-tests-azure-sas
    command: |-
      set -euo pipefail
      set +x
      #VAULT_TOKEN=$$(vault write -field=token auth/approle/login role_id=$$VAULT_ROLE_ID secret_id=$$VAULT_SECRET_ID)
      export VAULT_TOKEN
      export data=$$(vault read -format=json secret/ci/elastic-elasticsearch/migrated/azure_thirdparty_sas_test_creds)
      export azure_storage_account=$$(echo $$data | jq -r .data.account_id)
      export azure_storage_sas_token=$$(echo $$data | jq -r .data.account_sas_token)
      unset data
      set -x

      .ci/scripts/run-gradle.sh azureThirdPartyTest
    timeout_in_minutes: 180
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
  - label: third-party-tests-gcs
    command: |-
      set -euo pipefail
      export google_storage_service_account=$$(pwd)/gcs_service_account.json

      set +x
      #VAULT_TOKEN=$$(vault write -field=token auth/approle/login role_id=$$VAULT_ROLE_ID secret_id=$$VAULT_SECRET_ID)
      export VAULT_TOKEN
      vault read -field=private_key_data gcp-elastic-ci-prod/key/elasticsearch-ci-thirdparty-gcs | base64 --decode > $$google_storage_service_account
      #unset VAULT_TOKEN
      set -x

      .ci/scripts/run-gradle.sh gcsThirdPartyTest
    timeout_in_minutes: 180
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
  - label: third-party-tests-s3
    command: |-
      set -euo pipefail

      set +x
      #VAULT_TOKEN=$$(vault write -field=token auth/approle/login role_id=$$VAULT_ROLE_ID secret_id=$$VAULT_SECRET_ID)
      export VAULT_TOKEN
      export data=$$(vault read -format=json aws-test/creds/elasticsearch-ci-s3)
      export amazon_s3_access_key=$$(echo $$data | jq -r .data.access_key)
      export amazon_s3_secret_key=$$(echo $$data | jq -r .data.secret_key)
      unset data
      set -x

      .ci/scripts/run-gradle.sh s3ThirdPartyTest
    timeout_in_minutes: 180
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
  - label: third-party-tests-geoip
    command: .ci/scripts/run-gradle.sh :modules:ingest-geoip:internalClusterTest -Dgeoip_use_service=true
    timeout_in_minutes: 180
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
