steps:
  - label: example-plugins
    command: |-
      cd $$WORKSPACE/plugins/examples

      $$WORKSPACE/.ci/scripts/run-gradle.sh build
    timeout_in_minutes: 180
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
