steps:
  - group: packaging-tests-windows
    steps:
      - label: "{{matrix.image}} / packaging-tests-windows"
        command: .ci\scripts\packaging-test-buildkite.ps1
        timeout_in_minutes: 180
        matrix:
          setup:
            image:
              - windows-2016
              - windows-2019
              - windows-2022
        agents:
          provider: gcp
          image: family/brian-elasticsearch-{{matrix.image}}
          imageProject: elastic-images-qa
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env: {}
  - group: platform-support-windows
    steps:
      - label: "{{matrix.image}} / {{matrix.GRADLE_TASK}} / platform-support-windows"
        command: bash -c '.ci/scripts/run-gradle.sh -Dbwc.checkout.align=true $$GRADLE_TASK'
        timeout_in_minutes: 180
        matrix:
          setup:
            image:
              - windows-2016
              - windows-2019
              - windows-2022
            GRADLE_TASK:
              - checkPart1
              - checkPart2
              - checkPart3
              - bwcTestSnapshots
              - checkRestCompat
        agents:
          provider: gcp
          image: family/brian-elasticsearch-{{matrix.image}}
          imageProject: elastic-images-qa
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          GRADLE_TASK: "{{matrix.GRADLE_TASK}}"
