steps:
  - label: single-processor-node-tests
    command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true -Dtests.configure_test_clusters_with_one_processor=true check
    timeout_in_minutes: 180
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      diskSizeGb: 350
      machineType: custom-32-98304
