steps:
  - group: platform-support-unix
    steps:
      - label: "{{matrix.image}} / platform-support-unix"
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true check
        matrix:
          setup:
            image:
              - family/brian-elasticsearch-centos-7
              - family/brian-elasticsearch-debian-10
              - family/brian-elasticsearch-debian-11
              - family/brian-elasticsearch-opensuse-leap-15
              - family/brian-elasticsearch-oraclelinux-7
              - family/brian-elasticsearch-oraclelinux-8
              - family/brian-elasticsearch-sles-12
              - family/brian-elasticsearch-sles-15
              - family/brian-elasticsearch-ubuntu-1804
              - family/brian-elasticsearch-ubuntu-2004
              - family/brian-elasticsearch-ubuntu-2022
              - family/brian-elasticsearch-rocky-8
              - family/brian-elasticsearch-rhel-7
              - family/brian-elasticsearch-rhel-8
              - family/brian-elasticsearch-rhel-9
              - family/brian-elasticsearch-almalinux-8
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          imageProject: elastic-images-qa
          machineType: custom-32-98304
        env: {}
  - group: platform-support-arm
    steps:
      - label: "{{matrix.image}} / {{matrix.GRADLE_TASK}} / platform-support-arm"
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true $$GRADLE_TASK
        matrix:
          setup:
            image: []
            GRADLE_TASK:
              - checkPart1
              - checkPart2
              - checkPart3
              - bwcTestSnapshots
              - checkRestCompat
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          imageProject: elastic-images-qa
          buildDirectory: /dev/shm/bk
          machineType: custom-32-98304
        env:
          GRADLE_TASK: "{{matrix.GRADLE_TASK}}"
