env:
  BUILD_NUMBER: $BUILDKITE_BUILD_NUMBER
  COMPOSE_HTTP_TIMEOUT: "120"
  JOB_BRANCH: $BUILDKITE_BRANCH
  GRADLEW: ./gradlew --parallel --scan --build-cache --no-watch-fs
    -Dorg.elasticsearch.build.cache.url=https://gradle-enterprise.elastic.co/cache/
  GRADLEW_BAT: ./gradlew.bat --parallel --scan --build-cache --no-watch-fs
    -Dorg.elasticsearch.build.cache.url=https://gradle-enterprise.elastic.co/cache/
steps:
  - label: eql-correctness
    command: >-
      set +x

      VAULT_TOKEN=$$(vault write -field=token auth/approle/login role_id=$$VAULT_ROLE_ID secret_id=$$VAULT_SECRET_ID)

      export VAULT_TOKEN

      export eql_test_credentials_file="$$(pwd)/x-pack/plugin/eql/qa/correctness/credentials.gcs.json"

      vault read -field=credentials.gcs.json secret/elasticsearch-ci/eql_test_credentials > $${eql_test_credentials_file}

      unset VAULT_TOKEN

      set -x


      .ci/scripts/run-gradle.sh :x-pack:plugin:eql:qa:correctness:check
    agents:
      provider: gcp
      image: family/core-ubuntu-2204
      buildDirectory: /dev/shm/bk
      machineType: custom-32-98304
      useVault: false
