agents:
  provider: gcp
  image: family/brian-elasticsearch-ubuntu-2022
  imageProject: elastic-images-qa
  buildDirectory: /dev/shm/bk
  machineType: custom-32-98304
  useVault: false
steps:
  - label: example-plugins
    command: |-
      cd $$WORKSPACE/plugins/examples

      $$WORKSPACE/.ci/scripts/run-gradle.sh build
