steps:
  - label: example-plugins
    command: |-
      cd plugins/examples

      .ci/scripts/run-gradle.sh build
    agents:
      provider: gcp
      image: family/core-ubuntu-2204
      buildDirectory: /dev/shm/bk
      machineType: custom-32-98304
      useVault: false
