agents:
  provider: gcp
  image: family/core-ubuntu-2204
  buildDirectory: /dev/shm/bk
  machineType: custom-32-98304
  useVault: false
steps:
  - group: platform-support-unix
    steps:
      - label: platform-support-unix
        command: $$WORKSPACE/.ci/scripts/run-gradle.sh -Dbwc.checkout.align=true check
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          buildDirectory: /dev/shm/bk
          machineType: custom-32-98304
          useVault: false
        matrix:
          setup:
            image:
              - family/core-centos-7
              - family/core-debian-10
              - family/core-debian-11
              - family/core-opensuse-leap-15
              - family/core-oraclelinux-7
              - family/core-oraclelinux-8
              - family/core-sles-12
              - family/core-sles-15
              - family/core-ubuntu-1804
              - family/core-ubuntu-2004
              - family/core-ubuntu-2204
              - family/core-rocky-8
              - family/core-rhel-7
              - family/core-rhel-8
              - family/core-rhel-9
              - family/core-almalinux-8
        env: {}
  - group: platform-support-arm
    steps:
      - label: platform-support-arm
        command: $$WORKSPACE/.ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          $$GRADLE_TASK
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          buildDirectory: /dev/shm/bk
          machineType: custom-32-98304
          useVault: false
        matrix:
          setup:
            image: []
            GRADLE_TASK:
              - checkPart1
              - checkPart2
              - checkPart3
              - bwcTestSnapshots
              - checkRestCompat
        env:
          GRADLE_TASK: "{{matrix.GRADLE_TASK}}"
