agents:
  provider: gcp
  image: family/core-ubuntu-2204
  buildDirectory: /dev/shm/bk
  machineType: custom-32-98304
  useVault: false
steps:
  - group: bwc
    steps:
      - label: bwc / 7.0.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.0.0
      - label: bwc / 7.0.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.0.1
      - label: bwc / 7.1.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.1.0
      - label: bwc / 7.1.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.1.1
      - label: bwc / 7.2.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.2.0
      - label: bwc / 7.2.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.2.1
      - label: bwc / 7.3.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.3.0
      - label: bwc / 7.3.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.3.1
      - label: bwc / 7.3.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.3.2
      - label: bwc / 7.4.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.4.0
      - label: bwc / 7.4.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.4.1
      - label: bwc / 7.4.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.4.2
      - label: bwc / 7.5.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.5.0
      - label: bwc / 7.5.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.5.1
      - label: bwc / 7.5.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.5.2
      - label: bwc / 7.6.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.6.0
      - label: bwc / 7.6.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.6.1
      - label: bwc / 7.6.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.6.2
      - label: bwc / 7.7.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.7.0
      - label: bwc / 7.7.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.7.1
      - label: bwc / 7.8.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.8.0
      - label: bwc / 7.8.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.8.1
      - label: bwc / 7.9.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.9.0
      - label: bwc / 7.9.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.9.1
      - label: bwc / 7.9.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.9.2
      - label: bwc / 7.9.3
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.9.3
      - label: bwc / 7.10.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.10.0
      - label: bwc / 7.10.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.10.1
      - label: bwc / 7.10.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.10.2
      - label: bwc / 7.11.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.11.0
      - label: bwc / 7.11.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.11.1
      - label: bwc / 7.11.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.11.2
      - label: bwc / 7.12.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.12.0
      - label: bwc / 7.12.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.12.1
      - label: bwc / 7.13.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.13.0
      - label: bwc / 7.13.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.13.1
      - label: bwc / 7.13.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.13.2
      - label: bwc / 7.13.3
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.13.3
      - label: bwc / 7.13.4
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.13.4
      - label: bwc / 7.14.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.14.0
      - label: bwc / 7.14.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.14.1
      - label: bwc / 7.14.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.14.2
      - label: bwc / 7.15.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.15.0
      - label: bwc / 7.15.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.15.1
      - label: bwc / 7.15.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.15.2
      - label: bwc / 7.16.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.16.0
      - label: bwc / 7.16.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.16.1
      - label: bwc / 7.16.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.16.2
      - label: bwc / 7.16.3
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.16.3
      - label: bwc / 7.17.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.0
      - label: bwc / 7.17.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.1
      - label: bwc / 7.17.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.2
      - label: bwc / 7.17.3
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.3
      - label: bwc / 7.17.4
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.4
      - label: bwc / 7.17.5
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.5
      - label: bwc / 7.17.6
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.6
      - label: bwc / 7.17.7
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.7
      - label: bwc / 7.17.8
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.8
      - label: bwc / 7.17.9
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.9
      - label: bwc / 7.17.10
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.10
      - label: bwc / 7.17.11
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 7.17.11
      - label: bwc / 8.0.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.0.0
      - label: bwc / 8.0.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.0.1
      - label: bwc / 8.1.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.1.0
      - label: bwc / 8.1.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.1.1
      - label: bwc / 8.1.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.1.2
      - label: bwc / 8.1.3
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.1.3
      - label: bwc / 8.2.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.2.0
      - label: bwc / 8.2.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.2.1
      - label: bwc / 8.2.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.2.2
      - label: bwc / 8.2.3
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.2.3
      - label: bwc / 8.3.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.3.0
      - label: bwc / 8.3.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.3.1
      - label: bwc / 8.3.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.3.2
      - label: bwc / 8.3.3
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.3.3
      - label: bwc / 8.4.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.4.0
      - label: bwc / 8.4.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.4.1
      - label: bwc / 8.4.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.4.2
      - label: bwc / 8.4.3
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.4.3
      - label: bwc / 8.5.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.5.0
      - label: bwc / 8.5.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.5.1
      - label: bwc / 8.5.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.5.2
      - label: bwc / 8.5.3
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.5.3
      - label: bwc / 8.6.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.6.0
      - label: bwc / 8.6.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.6.1
      - label: bwc / 8.6.2
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.6.2
      - label: bwc / 8.7.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.7.0
      - label: bwc / 8.7.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.7.1
      - label: bwc / 8.8.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.8.0
      - label: bwc / 8.8.1
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.8.1
      - label: bwc / 8.9.0
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true
          v$$BWC_VERSION#bwcTest
        env:
          BWC_VERSION: 8.9.0
