agents:
  provider: gcp
  image: family/brian-elasticsearch-ubuntu-2004
  imageProject: elastic-images-qa
  buildDirectory: /dev/shm/bk
  machineType: custom-32-98304
steps:
  - group: bwc-snapshots-windows
    steps:
      - label: "{{matrix.BWC_VERSION}} / bwc-snapshots-windows"
        command: >
          del /f /s /q %USERPROFILE%\.gradle\init.d\*.*

          mkdir %USERPROFILE%\.gradle\init.d

          copy .ci\init.gradle %USERPROFILE%\.gradle\init.d\

          (
            echo call %GRADLEW_BAT% --max-workers=4 -Dbwc.checkout.align=true v%BWC_VERSION%#bwcTest ^|^| exit /b 1
          ) 
        matrix:
          setup:
            BWC_VERSION:
              - 7.17.11
              - 8.8.2
              - 8.9.0
        agents:
          provider: gcp
          image: family/core-windows-2022
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          BWC_VERSION: "{{matrix.BWC_VERSION}}"
  - group: packaging-tests-windows-nojdk
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} /
          packaging-tests-windows-nojdk"
        command: >
          del /f /s /q %USERPROFILE%\.gradle\init.d\*.*

          mkdir %USERPROFILE%\.gradle\init.d

          copy .ci\init.gradle %USERPROFILE%\.gradle\init.d\

          (
             echo powershell.exe .\.ci\scripts\packaging-test.ps1 -GradleTasks destructiveDistroTest.%PACKAGING_TASK%   ^|^| exit /b 1
          ) 
        matrix:
          setup:
            image:
              - family/core-windows-2012-r2
              - family/core-windows-2016
              - family/core-windows-2019
              - family/core-windows-2022
            PACKAGING_TASK:
              - default-windows-archive
              - default-windows-archive-no-jdk
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
  - group: packaging-tests-windows-sample-nojdk
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} /
          packaging-tests-windows-sample-nojdk"
        command: >
          del /f /s /q %USERPROFILE%\.gradle\init.d\*.*

          mkdir %USERPROFILE%\.gradle\init.d

          copy .ci\init.gradle %USERPROFILE%\.gradle\init.d\

          (
             echo powershell.exe .\.ci\scripts\packaging-test.ps1 -GradleTasks destructiveDistroTest.%PACKAGING_TASK%   ^|^| exit /b 1
          ) 
        matrix:
          setup:
            image:
              - family/core-windows-2019
            PACKAGING_TASK:
              - default-windows-archive
              - default-windows-archive-no-jdk
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
  - group: packaging-tests-windows-sample
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} /
          packaging-tests-windows-sample"
        command: >
          del /f /s /q %USERPROFILE%\.gradle\init.d\*.*

          mkdir %USERPROFILE%\.gradle\init.d

          copy .ci\init.gradle %USERPROFILE%\.gradle\init.d\

          (
             echo powershell.exe .\.ci\scripts\packaging-test.ps1 -GradleTasks destructiveDistroTest.%PACKAGING_TASK%   ^|^| exit /b 1
          ) 
        matrix:
          setup:
            image:
              - family/core-windows-2019
            PACKAGING_TASK:
              - default-windows-archive
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
  - group: packaging-tests-windows
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} / packaging-tests-windows"
        command: >
          del /f /s /q %USERPROFILE%\.gradle\init.d\*.*

          mkdir %USERPROFILE%\.gradle\init.d

          copy .ci\init.gradle %USERPROFILE%\.gradle\init.d\

          (
             echo powershell.exe .\.ci\scripts\packaging-test.ps1 -GradleTasks destructiveDistroTest.%PACKAGING_TASK%   ^|^| exit /b 1
          ) 
        matrix:
          setup:
            image:
              - family/core-windows-2012-r2
              - family/core-windows-2016
              - family/core-windows-2019
              - family/core-windows-2022
            PACKAGING_TASK:
              - default-windows-archive
        agents:
          provider: gcp
          image: "{{matrix.image}}"
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
  - label: part-1-windows
    command: >
      del /f /s /q %USERPROFILE%\.gradle\init.d\*.*

      mkdir %USERPROFILE%\.gradle\init.d

      copy .ci\init.gradle %USERPROFILE%\.gradle\init.d\

      (
        echo call %GRADLEW_BAT% --max-workers=4 -Dbwc.checkout.align=true %GRADLE_TASK% ^|^| exit /b 1
      ) 
    agents:
      provider: gcp
      image: family/core-windows-2022
      machineType: custom-32-98304
      diskType: pd-ssd
      diskSizeGb: 350
  - label: part-2-windows
    command: >
      del /f /s /q %USERPROFILE%\.gradle\init.d\*.*

      mkdir %USERPROFILE%\.gradle\init.d

      copy .ci\init.gradle %USERPROFILE%\.gradle\init.d\

      (
        echo call %GRADLEW_BAT% --max-workers=4 -Dbwc.checkout.align=true %GRADLE_TASK% ^|^| exit /b 1
      ) 
    agents:
      provider: gcp
      image: family/core-windows-2022
      machineType: custom-32-98304
      diskType: pd-ssd
      diskSizeGb: 350
  - label: part-3-windows
    command: >
      del /f /s /q %USERPROFILE%\.gradle\init.d\*.*

      mkdir %USERPROFILE%\.gradle\init.d

      copy .ci\init.gradle %USERPROFILE%\.gradle\init.d\

      (
        echo call %GRADLEW_BAT% --max-workers=4 -Dbwc.checkout.align=true %GRADLE_TASK% ^|^| exit /b 1
      ) 
    agents:
      provider: gcp
      image: family/core-windows-2022
      machineType: custom-32-98304
      diskType: pd-ssd
      diskSizeGb: 350
