agents:
  provider: gcp
  image: family/brian-elasticsearch-ubuntu-2022
  imageProject: elastic-images-qa
  buildDirectory: /dev/shm/bk
  machineType: custom-32-98304
  useVault: false
steps:
  - label: eql-correctness
    command: >-
      set +x

      VAULT_TOKEN=$$(vault write -field=token auth/approle/login role_id=$$VAULT_ROLE_ID secret_id=$$VAULT_SECRET_ID)

      export VAULT_TOKEN

      export eql_test_credentials_file="$$(pwd)/x-pack/plugin/eql/qa/correctness/credentials.gcs.json"

      vault read -field=credentials.gcs.json secret/elasticsearch-ci/eql_test_credentials > $${eql_test_credentials_file}

      unset VAULT_TOKEN

      set -x


      $$WORKSPACE/.ci/scripts/run-gradle.sh :x-pack:plugin:eql:qa:correctness:check
