steps:
  - group: bwc-snapshots-windows
    steps:
      - label: "{{matrix.BWC_VERSION}} / bwc-snapshots-windows"
        command: '& .buildkite\generated-scripts\4ef3241cf6b8dbbae758f32a006b0bc0.bat'
        timeout_in_minutes: 180
        matrix:
          setup:
            BWC_VERSION:
              - 7.17.12
              - 8.8.3
              - 8.9.0
              - 8.10.0
        agents:
          provider: gcp
          image: family/brian-elasticsearch-windows-2022
          imageProject: elastic-images-qa
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          BWC_VERSION: "{{matrix.BWC_VERSION}}"
  - group: packaging-tests-windows
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} / packaging-tests-windows"
        command: '& .buildkite\generated-scripts\ca6b2b9c7738eac3d32fd7cd4ac2faa8.bat'
        timeout_in_minutes: 180
        matrix:
          setup:
            image:
              - windows-2016
              - windows-2019
              - windows-2022
            PACKAGING_TASK:
              - default-windows-archive
        agents:
          provider: gcp
          image: family/brian-elasticsearch-{{matrix.image}}
          imageProject: elastic-images-qa
          machineType: custom-32-98304
          diskType: pd-ssd
          diskSizeGb: 350
        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
  - label: part-1-windows
    command: '& .buildkite\generated-scripts\0ed44aaeab2687b9cc3da467568468e5.bat'
    timeout_in_minutes: 180
    agents:
      provider: gcp
      image: family/brian-elasticsearch-windows-2022
      imageProject: elastic-images-qa
      machineType: custom-32-98304
      diskType: pd-ssd
      diskSizeGb: 350
  - label: part-2-windows
    command: '& .buildkite\generated-scripts\0ed44aaeab2687b9cc3da467568468e5.bat'
    timeout_in_minutes: 180
    agents:
      provider: gcp
      image: family/brian-elasticsearch-windows-2022
      imageProject: elastic-images-qa
      machineType: custom-32-98304
      diskType: pd-ssd
      diskSizeGb: 350
  - label: part-3-windows
    command: '& .buildkite\generated-scripts\0ed44aaeab2687b9cc3da467568468e5.bat'
    timeout_in_minutes: 180
    agents:
      provider: gcp
      image: family/brian-elasticsearch-windows-2022
      imageProject: elastic-images-qa
      machineType: custom-32-98304
      diskType: pd-ssd
      diskSizeGb: 350
