# Synchronizes all pushes to upstream 'main' branch local 'main' branch.
# Creates a PR that automatically merges main with the ESQL branch (esql/lang).
name: "Sync development branches"
on:
  schedule:
      - cron: '40 4 * * *'
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream main

    steps:
      - name: Checkout target repo
        id: checkout
        uses: actions/checkout@v2.4.2
        with:
          ref: main

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.3
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.ELASTICSEARCHMACHINE }}
          upstream_sync_branch: main
          upstream_sync_repo: elastic/elasticsearch

      - name: Create ESQL PR
        id: pr-create-esql
        if: steps.sync.outputs.has_new_commits == 'true'
        uses: thomaseizinger/create-pull-request@1.2.2
        with:
           head: main
           base: esql/lang
           title: "🤖 ESQL: Merge upstream"
           body: ":robot: Generated PR to keep ESQL development branch up to date"
           labels: "upstream-sync,esql"
           github_token: ${{ secrets.ELASTICSEARCHMACHINE }}

## Merging done by bot on CI check completion 
## -- auto-merge label removed, since bot squash-merges, later resulting in
##    conflicts
##
#      - name: Merge ESQL PR
#        id: pr-merge-esql
#        if: steps.pr-create-esql.outputs.created == 'true'
#        uses: juliangruber/merge-pull-request-action@v1.1.0
#        with:
#           method: merge
#           number: ${{ steps.pr-create-esql.outputs.number }}
#           github-token: ${{ secrets.ELASTICSEARCHMACHINE }}

      - name: Merge ESQL PR
        id: pr-mark-auto-merge
        if: steps.pr-create-esql.outputs.created == 'true'
        uses: alexwilson/enable-github-automerge-action@1.0.0
        with:
           github-token: ${{ secrets.ELASTICSEARCHMACHINE }}
